baseURL = "https://bebe.tole.es"
title = "Últimas ofertas"
theme = "portfolio"
languageCode = "es-es"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
paginate = 30
# disableKinds = ["RSS"]
enableRobotsTXT = true

[sitemap]
  changefreq = "hourly"
  filename = "sitemap.xml"
  priority = 0.5

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "sea"
  description = "Todo rebajado!"
  copyright = ""
  sidebarAbout = []
  # Enable Google Analytics by entering your tracking code
  gtag="G-1BKKRPRJ18"
  yandex="2e182b1358b7eb92"

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Raíz  "
  url = "/"
  home = true


  [outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
